version: "3"

services:
  garmin-influxdb:
    build: .
    environment:
      INFLUXDB_HOST: <influxdb_host>
      INFLUXDB_PORT: <influxdb_port>
      INFLUXDB_USERNAME: <influxdb_username>
      INFLUXDB_PASSWORD: <influxdb_password>
    restart: unless-stopped
