version: '3'

services:
  garmin-influxdb:
    build: .
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_DATABASE=garmin
      - INFLUXDB_USERNAME=root
      - INFLUXDB_PASSWORD=pass
      - INFLUXDB_TAGS=garmin_device
      - GARMIN_USERNAME=your_garmin_username
      - GARMIN_PASSWORD=your_garmin_password
